# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/branch.ui'
#
# Created: Sun Jan 17 09:12:14 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from bzrlib.plugins.qbzr.lib.i18n import gettext


class Ui_BranchForm(object):
    def setupUi(self, BranchForm):
        BranchForm.setObjectName("BranchForm")
        BranchForm.resize(349, 207)
        self.verticalLayout = QtGui.QVBoxLayout(BranchForm)
        self.verticalLayout.setMargin(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(BranchForm)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.from_label = QtGui.QLabel(self.groupBox)
        self.from_label.setObjectName("from_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.from_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.from_location = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_location.sizePolicy().hasHeightForWidth())
        self.from_location.setSizePolicy(sizePolicy)
        self.from_location.setEditable(True)
        self.from_location.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.from_location.setObjectName("from_location")
        self.horizontalLayout_2.addWidget(self.from_location)
        self.from_picker = QtGui.QPushButton(self.groupBox)
        self.from_picker.setObjectName("from_picker")
        self.horizontalLayout_2.addWidget(self.from_picker)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.to_label = QtGui.QLabel(self.groupBox)
        self.to_label.setObjectName("to_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.to_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.to_location = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_location.sizePolicy().hasHeightForWidth())
        self.to_location.setSizePolicy(sizePolicy)
        self.to_location.setEditable(True)
        self.to_location.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.to_location.setObjectName("to_location")
        self.horizontalLayout_3.addWidget(self.to_location)
        self.to_picker = QtGui.QPushButton(self.groupBox)
        self.to_picker.setObjectName("to_picker")
        self.horizontalLayout_3.addWidget(self.to_picker)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(BranchForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bind = QtGui.QCheckBox(self.groupBox_2)
        self.bind.setObjectName("bind")
        self.verticalLayout_2.addWidget(self.bind)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.revision_label = QtGui.QLabel(self.groupBox_2)
        self.revision_label.setObjectName("revision_label")
        self.horizontalLayout.addWidget(self.revision_label)
        self.revision = QtGui.QLineEdit(self.groupBox_2)
        self.revision.setObjectName("revision")
        self.horizontalLayout.addWidget(self.revision)
        spacerItem = QtGui.QSpacerItem(78, 37, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.from_label.setBuddy(self.from_location)
        self.to_label.setBuddy(self.to_location)
        self.revision_label.setBuddy(self.revision)

        self.retranslateUi(BranchForm)
        QtCore.QObject.connect(BranchForm, QtCore.SIGNAL("disableUi(bool)"), self.groupBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(BranchForm)

    def retranslateUi(self, BranchForm):
        BranchForm.setWindowTitle(gettext("Branch"))
        self.groupBox.setTitle(gettext("Locations"))
        self.from_label.setText(gettext("&From:"))
        self.from_picker.setText(gettext("Browse..."))
        self.to_label.setText(gettext("&To:"))
        self.to_picker.setText(gettext("Browse..."))
        self.groupBox_2.setTitle(gettext("Options"))
        self.bind.setText(gettext("Bind new branch to parent location"))
        self.revision_label.setText(gettext("&Revision:"))

