# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/sysinfo.ui'
#
# Created: Thu Jun  4 10:55:53 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 455)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 411, 272))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bazaar_library = QtGui.QGroupBox(self.widget)
        self.bazaar_library.setFlat(False)
        self.bazaar_library.setObjectName("bazaar_library")
        self.formLayout = QtGui.QFormLayout(self.bazaar_library)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.bazaar_library)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.bzr_version = QtGui.QLabel(self.bazaar_library)
        self.bzr_version.setObjectName("bzr_version")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.bzr_version)
        self.label_3 = QtGui.QLabel(self.bazaar_library)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.bzr_lib_path = QtGui.QLabel(self.bazaar_library)
        self.bzr_lib_path.setObjectName("bzr_lib_path")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.bzr_lib_path)
        self.verticalLayout.addWidget(self.bazaar_library)
        self.bazaar_configuration = QtGui.QGroupBox(self.widget)
        self.bazaar_configuration.setObjectName("bazaar_configuration")
        self.formLayout_2 = QtGui.QFormLayout(self.bazaar_configuration)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtGui.QLabel(self.bazaar_configuration)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.bzr_config_dir = QtGui.QLabel(self.bazaar_configuration)
        self.bzr_config_dir.setObjectName("bzr_config_dir")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.bzr_config_dir)
        self.label_4 = QtGui.QLabel(self.bazaar_configuration)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.bzr_log_file = QtGui.QLabel(self.bazaar_configuration)
        self.bzr_log_file.setObjectName("bzr_log_file")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.bzr_log_file)
        self.verticalLayout.addWidget(self.bazaar_configuration)
        self.python_interpreter = QtGui.QGroupBox(self.widget)
        self.python_interpreter.setMinimumSize(QtCore.QSize(329, 0))
        self.python_interpreter.setObjectName("python_interpreter")
        self.formLayout_3 = QtGui.QFormLayout(self.python_interpreter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtGui.QLabel(self.python_interpreter)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.python_version = QtGui.QLabel(self.python_interpreter)
        self.python_version.setObjectName("python_version")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.python_version)
        self.label_9 = QtGui.QLabel(self.python_interpreter)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.python_file = QtGui.QLabel(self.python_interpreter)
        self.python_file.setObjectName("python_file")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.python_file)
        self.label_7 = QtGui.QLabel(self.python_interpreter)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.python_lib_dir = QtGui.QLabel(self.python_interpreter)
        self.python_lib_dir.setObjectName("python_lib_dir")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.python_lib_dir)
        self.verticalLayout.addWidget(self.python_interpreter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bazaar_library.setTitle(QtGui.QApplication.translate("MainWindow", "Bazaar Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_version.setText(QtGui.QApplication.translate("MainWindow", "(bzr-version)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_lib_path.setText(QtGui.QApplication.translate("MainWindow", "(bzr-lib-path)", None, QtGui.QApplication.UnicodeUTF8))
        self.bazaar_configuration.setTitle(QtGui.QApplication.translate("MainWindow", "Bazaar Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_config_dir.setText(QtGui.QApplication.translate("MainWindow", "(bzr-config-dir)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Log File:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_log_file.setText(QtGui.QApplication.translate("MainWindow", "(bzr-log-file)", None, QtGui.QApplication.UnicodeUTF8))
        self.python_interpreter.setTitle(QtGui.QApplication.translate("MainWindow", "Python Interpreter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_version.setText(QtGui.QApplication.translate("MainWindow", "(python-version)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_file.setText(QtGui.QApplication.translate("MainWindow", "(python-file)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Library:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_lib_dir.setText(QtGui.QApplication.translate("MainWindow", "(python-lib-dir)", None, QtGui.QApplication.UnicodeUTF8))

