# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/sysinfo.ui'
#
# Created: Wed Jun 10 20:42:32 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 375)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 21, 391, 312))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bazaar_library = QtGui.QGroupBox(self.widget)
        self.bazaar_library.setFlat(False)
        self.bazaar_library.setObjectName("bazaar_library")
        self.gridLayout = QtGui.QGridLayout(self.bazaar_library)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.bazaar_library)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.bzr_version = QtGui.QLabel(self.bazaar_library)
        self.bzr_version.setObjectName("bzr_version")
        self.gridLayout.addWidget(self.bzr_version, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.bazaar_library)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.bzr_lib_path = QtGui.QLabel(self.bazaar_library)
        self.bzr_lib_path.setMinimumSize(QtCore.QSize(300, 0))
        self.bzr_lib_path.setObjectName("bzr_lib_path")
        self.gridLayout.addWidget(self.bzr_lib_path, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.bazaar_library)
        self.bazaar_configuration = QtGui.QGroupBox(self.widget)
        self.bazaar_configuration.setObjectName("bazaar_configuration")
        self.gridLayout_2 = QtGui.QGridLayout(self.bazaar_configuration)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.bazaar_configuration)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.bzr_config_dir = QtGui.QLabel(self.bazaar_configuration)
        self.bzr_config_dir.setObjectName("bzr_config_dir")
        self.gridLayout_2.addWidget(self.bzr_config_dir, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.bazaar_configuration)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.bzr_log_file = QtGui.QLabel(self.bazaar_configuration)
        self.bzr_log_file.setMinimumSize(QtCore.QSize(300, 0))
        self.bzr_log_file.setObjectName("bzr_log_file")
        self.gridLayout_2.addWidget(self.bzr_log_file, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.bazaar_configuration)
        self.python_interpreter = QtGui.QGroupBox(self.widget)
        self.python_interpreter.setMinimumSize(QtCore.QSize(0, 0))
        self.python_interpreter.setObjectName("python_interpreter")
        self.gridLayout_3 = QtGui.QGridLayout(self.python_interpreter)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.python_interpreter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.python_version = QtGui.QLabel(self.python_interpreter)
        self.python_version.setObjectName("python_version")
        self.gridLayout_3.addWidget(self.python_version, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.python_interpreter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.python_file = QtGui.QLabel(self.python_interpreter)
        self.python_file.setObjectName("python_file")
        self.gridLayout_3.addWidget(self.python_file, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.python_interpreter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.python_lib_dir = QtGui.QLabel(self.python_interpreter)
        self.python_lib_dir.setMinimumSize(QtCore.QSize(300, 0))
        self.python_lib_dir.setObjectName("python_lib_dir")
        self.gridLayout_3.addWidget(self.python_lib_dir, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.python_interpreter)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "System Information", None, QtGui.QApplication.UnicodeUTF8))
        self.bazaar_library.setTitle(QtGui.QApplication.translate("MainWindow", "Bazaar Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_version.setText(QtGui.QApplication.translate("MainWindow", "(bzr-version)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_lib_path.setText(QtGui.QApplication.translate("MainWindow", "(bzr-lib-path)", None, QtGui.QApplication.UnicodeUTF8))
        self.bazaar_configuration.setTitle(QtGui.QApplication.translate("MainWindow", "Bazaar Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_config_dir.setText(QtGui.QApplication.translate("MainWindow", "(bzr-config-dir)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Log File:", None, QtGui.QApplication.UnicodeUTF8))
        self.bzr_log_file.setText(QtGui.QApplication.translate("MainWindow", "(bzr-log-file)", None, QtGui.QApplication.UnicodeUTF8))
        self.python_interpreter.setTitle(QtGui.QApplication.translate("MainWindow", "Python Interpreter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_version.setText(QtGui.QApplication.translate("MainWindow", "(python-version)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_file.setText(QtGui.QApplication.translate("MainWindow", "(python-file)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Library:", None, QtGui.QApplication.UnicodeUTF8))
        self.python_lib_dir.setText(QtGui.QApplication.translate("MainWindow", "(python-lib-dir)", None, QtGui.QApplication.UnicodeUTF8))

