from PyQt4.QtCore import *
from PyQt4.QtGui import *
from PyQt4.QtNetwork import *
from PyQt4.QtOpenGL import *
from PyQt4.QtSql import *
from PyQt4.QtSvg import *
from PyQt4.QtTest import *
from PyQt4.QtXml import *
from PyQt4.QtAssistant import *
